services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=simple_db'
      - 'MARIADB_USER=username'
      - 'MARIADB_PASSWORD=usersecret'
      - 'MARIADB_ROOT_PASSWORD=supersecret'
    ports:
      - '3306'
    volumes:
        - ./db-content:/var/lib/mysql